# =======================================================================================
# HYPRPAPER.CONF
# =======================================================================================

wallpaper {
    monitor  = DP-3
    path     = /home/Jogeir/hdd/Pictures/
    fit_mode = cover
    order    = random
}

splash = false
