background {
    monitor =
    path = ~/Pictures/lockscreen.jpg
    blur_passes = 2
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 3
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(255, 255, 255)
    placeholder_text = <span>Password...</span>
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 55
    font_family = JetBrainsMono Nerd Font
    position = 0, 300
    halign = center
    valign = center
}
