set -g set-clipboard on #Use system clipboard
set -g mouse on     #Enable mouse support
set -g status-interval 3 # update statusbar every 3 seconds

# Start windows and panes index at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # renumbers windows when one gets closed

# Refresh tmux config with r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Set terminal color to get starship working with tmux
set-option -g default-terminal "tmux-256color"
# Enable 24-bit (true color) passthrough for the outer terminal
set -as terminal-features ",xterm-256color:RGB"

# Apperance
set -g status-justify centre
set-option -g status-position bottom
set -g status-style fg=white,bg=black
setw -g window-status-style fg=white,bg=black

# Switch windows with Alt + number (0-9)
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
bind-key -n M-0 select-window -t 0
